- route:
    from:
      uri: kamelet:postgresql-source
      parameters:
        serverName: "{{configmap:cm-postgres/host}}"
        serverPort: 5432
        username: "{{configmap:cm-postgres/username}}"
        password: "{{configmap:cm-postgres/password}}"
        query: select * from test;
        databaseName: test
        delay: 5000
      steps:
        - log:
            message: ${body}
