## GCP Secrets Manager Vault on OCP through External Secrets Operator infrastructure

In this sample you'll use the Kubernetes Secrets properties from Camel in combination with External Secrets Operator GCP Secrets Manager Provider

## Install JBang

First install JBang according to https://www.jbang.dev

When JBang is installed then you should be able to run from a shell:

[source,sh]
----
$ jbang --version
----

This will output the version of JBang.

To run this example you can either install Camel on JBang via:

[source,sh]
----
$ jbang app install camel@apache/camel
----

Which allows to run CamelJBang with `camel` as shown below.

## Preparing the project

We'll connect to the `ext-sec-gcp` project and check the installation status. To change project, open a terminal tab and type the following command:

```
oc new-project ext-sec-gcp
```

## Setting up Database

This example uses a PostgreSQL database. We want to install it on the project `ext-sec-gcp`. We can go to the OpenShift 4.x WebConsole page, use the OperatorHub menu item on the left hand side menu and use it to find and install "Crunchy Postgres for Kubernetes". This will install the operator and may take a couple of minutes to install.

Once the operator is installed, we can create a new database using

```
oc create -f ./infra/postgres.yaml -n ext-sec-gcp
```

We connect to the database pod to create a table and add data to be extracted later.

```
oc rsh $(oc get pods -l postgres-operator.crunchydata.com/role=master -o name)
```

```
psql -U postgres test \
-c "CREATE TABLE test (data TEXT PRIMARY KEY);
INSERT INTO test(data) VALUES ('hello'), ('world');
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgresadmin;"
```

Now let's change the password.

```
psql -U postgres -c "ALTER USER postgresadmin PASSWORD 'masteradmin1234*';"
```

```
exit
```

Now you need to create a project on the Google Cloud console and enable the Secrets Manager API on it.

After that you'll need to create a service account with permission to use at least the Secrets Manager API. Once created, you should obtain a service account key file in Json format.

Now we need to create the secret payload. Open the file postgresCreds.json and place the related exported value into the related field. You should have something like:

```
{
  "username": "user",
  "password": "pwd",
  "host": "postgres-primary.ext-sec-gcp.svc"
}
```

This complete the Database setup.

## Externalize secrets into External Secret operator infra

In your namespace install the External Secret operator with latest version.

Now run the following:

```
oc apply -f ./infra/operatorConfig.yaml -n ext-sec-gcp
```

This should install your operator correctly for OCP.

Now you need to create a project in your Google Cloud Console and enable Secrets Manager API.

Now create the secret with the Gcloud CLI or with the console:

```
gcloud secrets create dbcred --project=<project_id>
```

And add a version of the secret

```
gcloud secrets versions add dbcred --data-file=postgresCreds.json --project=<project_id>
```

Then create a service account with Secret Manager Admin role and export a Json Service account key.

Copy the value and place it in gcp-secret-sa.yaml file in place of <json> placeholder.

Now run:

```
oc apply -f ./infra/gcp-secret-sa.yaml -n ext-sec-gcp
```

Once everything is done you can create your secret

```
oc apply -f ./infra/basic-secret-store.yaml -n ext-sec-gcp
```

and create the secret

```
oc apply -f ./infra/basic-external-secret.yaml -n ext-sec-gcp
```

To be sure everything is fine you should find a secret named dbsec in your secrets for the namespace ext-secrets-camel-sql-refresh.

Now we need to give application the ability to read secrets from the cluster

```
oc create clusterrole secretadmin --verb=get --verb=list --resource=secret --namespace=ext-sec-gcp
```

or alternatively you can run

```
oc apply -f ./infra/secretpermission.yaml
```

## Deploy to OCP

Once the process complete

```
./mvnw install -Dquarkus.openshift.deploy=true
```

Once everything is complete you should be able to access the logs with the following command:

```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec -a "java" java -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
INFO running in /deployments
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-08-29 10:43:39,897 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2024-08-29 10:43:39,900 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.6.0 is starting
2024-08-29 10:43:40,002 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
2024-08-29 10:43:40,003 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.main.routesIncludePattern=camel/sql-to-log.camel.yaml
2024-08-29 10:43:40,189 INFO  [org.apa.cam.com.kub.pro.BasePropertiesFunction] (main) KubernetesClient using masterUrl: https://172.21.0.1:443/ with namespace: ext-sec-gcp
2024-08-29 10:43:40,872 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.6.0 (camel-1) is starting
2024-08-29 10:43:40,900 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Property-placeholders summary
2024-08-29 10:43:40,901 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [stgresql-source.kamelet.yaml] query=select * from test;
2024-08-29 10:43:40,901 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [stgresql-source.kamelet.yaml] dsBean=dsBean-1
2024-08-29 10:43:40,901 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [stgresql-source.kamelet.yaml] delay=120000
2024-08-29 10:43:40,901 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [stgresql-source.kamelet.yaml] password=xxxxxx
2024-08-29 10:43:40,902 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [stgresql-source.kamelet.yaml] serverName=postgres-primary.ext-sec-gcp.svc
2024-08-29 10:43:40,902 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [stgresql-source.kamelet.yaml] databaseName=test
2024-08-29 10:43:40,902 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [stgresql-source.kamelet.yaml] username=xxxxxx
2024-08-29 10:43:40,904 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (total:1 started:1 kamelets:1)
2024-08-29 10:43:40,904 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (kamelet://postgresql-source)
2024-08-29 10:43:40,904 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.6.0 (camel-1) started in 31ms (build:0ms init:0ms start:31ms)
2024-08-29 10:43:40,956 INFO  [io.quarkus] (main) camel-kubernetes-vault 1.0-SNAPSHOT on JVM (powered by Quarkus 3.12.2) started in 3.148s. Listening on: http://0.0.0.0:8080
2024-08-29 10:43:40,957 INFO  [io.quarkus] (main) Profile prod activated. 
2024-08-29 10:43:40,957 INFO  [io.quarkus] (main) Installed features: [agroal, camel-attachments, camel-core, camel-jackson, camel-kamelet, camel-kubernetes, camel-log, camel-microprofile-health, camel-platform-http, camel-rest, camel-rest-openapi, camel-sql, camel-yaml-dsl, cdi, kubernetes, kubernetes-client, narayana-jta, smallrye-context-propagation, smallrye-health, vertx]
2024-08-29 10:43:42,286 INFO  [route1] (Camel (camel-1) thread #1 - sql://select%20*%20from%20test;) {"data":"hello"}
2024-08-29 10:43:42,289 INFO  [route1] (Camel (camel-1) thread #1 - sql://select%20*%20from%20test;) {"data":"world"}
```

## Auto refresh of the secret and modification

To show how to refresh works we'll need to change the password for postgresadmin user on our Database.

First run the following command:

```
oc rsh $(oc get pods -l postgres-operator.crunchydata.com/role=master -o name)
```

Now you need to change the password inside the container

```
sh-4.4$ psql -U postgres -c "ALTER USER postgresadmin PASSWORD 'masteradmin12345*';"
```

Modify the postgresCreds.json file with the new password and add a version of the secret

```
gcloud secrets versions add dbcred --data-file=postgresCreds.json --project=<project_id>
```

Now get back to the log and you should see the following entries:

```
2024-08-27 11:59:18,053 INFO  [route1] (Camel (camel-1) thread #1 - sql://select%20*%20from%20test;) {"data":"hello"}
2024-08-27 11:59:18,053 INFO  [route1] (Camel (camel-1) thread #1 - sql://select%20*%20from%20test;) {"data":"world"}
2024-08-27 12:01:18,061 INFO  [route1] (Camel (camel-1) thread #1 - sql://select%20*%20from%20test;) {"data":"hello"}
2024-08-27 12:01:18,062 INFO  [route1] (Camel (camel-1) thread #1 - sql://select%20*%20from%20test;) {"data":"world"}
```

If you look at the description of external secret you should see the secret has been updated:

```
oc describe es example
.
.
.
.
Status:
  Binding:
    Name:  authsecdb
  Conditions:
    Last Transition Time:   2024-08-27T09:44:24Z
    Message:                Secret was synced
    Reason:                 SecretSynced
    Status:                 True
    Type:                   Ready
  Refresh Time:             2024-08-27T12:02:44Z
  Synced Resource Version:  1-2d524f20b9a51515951be6fe2bc907a8
Events:
  Type    Reason   Age    From              Message
  ----    ------   ----   ----              -------
  Normal  Created  138m   external-secrets  Created Secret
  Normal  Updated  3m17s  external-secrets  Updated Secret

```
