apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: ext-sec-gcp
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-store
    kind: SecretStore
  target:
    name: dbcred
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: dbcred
